version: "3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8222:80"
    volumes:
      - .:/var/www
    restart: always
    environment:
     UPLOAD_LIMIT: 200M
